services:
  # PHP service
  php:
    build: .
    container_name: racitelcom_payroll_php_prod
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - my-network
      
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: racitelcom_payroll_mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./payroll.sql:/docker-entrypoint-initdb.d/payroll.sql

  # PHPMyAdmin service 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: racitelcom_payroll_phpmyadmin_prod
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS} 
    ports:
      - "8080:80"
    networks:
      - my-network
    depends_on:
    - mysql
    volumes:
      - mysql-data:/var/lib/mysql
  

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
